# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaiYiToken' do
  
   pod 'Masonry'
   pod 'AFNetworking', '~> 4.0'
   pod 'YYKit'
   pod 'MBProgressHUD'
   pod 'MJRefresh'
   pod 'JVFloatLabeledTextField'
   pod 'SDWebImage'  
   pod 'SAMKeychain'

   #扫描二维码
   pod 'SGQRCode'
   #自定义的搜索功能
   pod 'PYSearch'
   #侧滑抽屉
   pod 'CWLateralSlide', '~> 1.6.1'
   #TableCell左右自定义滑动
   pod 'MGSwipeTableCell'
   #pod 'UMengAnalytics-NO-IDFA'#无IDFA版SDK（请根据需要选择其中一个）
   #pod 'Toast', '~> 4.0.0' #页面提示
   #友盟
   #pod 'UMCCommon'
   #pod 'UMCCommonLog'
   #pod 'UMCSecurityPlugins'
   #pod 'UMCAnalytics'
   #pod 'UMCErrorCatch'

   pod 'Realm'

   pod 'HWPanModal'
   pod 'IQKeyboardManager'
   pod 'CYLTabBarController'
   pod 'XFDialogBuilder', '~> 1.2.9'
   #pod 'YYModel'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


#商城依赖框架
   pod 'SVProgressHUD'
   pod 'MJExtension'
   pod 'SDCycleScrollView'
   pod 'ZYCornerRadius'
   pod 'TZImagePickerController'
   pod 'CDDPagerController'

   pod 'PYSearch'
   pod 'secp256k1_ios'
   pod 'FMDB'
   pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end

